# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats: all

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .

build:
  os: ubuntu-20.04
  tools:
    python: '3.9'

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true